
spring.datasource.url=jdbc:postgresql://localhost:5432/croche_db
spring.datasource.username=postgres
spring.datasource.password=D3str0y3r


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true